export const themes = {
  "solarized-dark": {
    "--planager-pink": "#d33682",
    "--planager-red": "#dc322f",
    "--planager-orange": "#cb4b16",
    "--planager-yellow": "#b58900",
    "--planager-green": "#859900",
    "--planager-cyan": "#2aa198",
    "--planager-blue": "#268bd2",
    "--planager-purple": "#6c71c4",
    "--planager-text-light": "#fdf6e3",
    "--planager-text-dark": "#002b36",
    "--planager-pipe": "#939393",
    "--planager-workspace-background": "#073642",
    "--planager-toolbar": "#002b36",
    "--planager-module-background": "#eee8d5",
  },
  dracula: {
    "--planager-pink": "#ff79c6",
    "--planager-red": "#ff5555",
    "--planager-orange": "#ffad55",
    "--planager-yellow": "#f1fa8c",
    "--planager-green": "#50fa7b",
    "--planager-cyan": "#8be9fd",
    "--planager-blue": "#4395d4",
    "--planager-purple": "#9674c8",
    "--planager-text-light": "#f8f8f2",
    "--planager-text-dark": "#282a36",
    "--planager-pipe": "#b7b7b7",
    "--planager-workspace-background": "#44475a",
    "--planager-toolbar": "#282a36",
    "--planager-module-background": "#f8f8f2",
    "--planager-module-background-accent": "#d5d5d5",
    "--planager-gray": "#848484",
  },
};
